[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@socket.io/redis-adapter", "redis"]
  
[[redirects]]
  from = "/api/socketio/*"
  to = "/.netlify/functions/socketio/:splat"
  status = 200

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
